### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by chrisbirdsall** [andrewheiss/SublimeStataEnhanced#27]
The build command broke for me at some point. I am using StataSE 13.1. I reverted Stata.sublime-build to what it looked like in 1.0.2 and now it seems to work:

```
{        
  "cmd": ["osascript -e 'try' -e 'tell application \"StataSE\" to activate & DoCommandAsync \"do $file\"' -e 'end try'"],
  "selector": "source.stata",
  "shell": true
}
```

**Comment by andrewheiss** [comment]
What do you mean by broke? Does it just open the do file in Stata without running it?

I think that's because I decided to have the build file work for Stata 11–13 and not just for 13 (since 11–12 don't support AppleScript commands like `DoCommandAsync`). The build file should work if change the `.do` file preferences [listed in the README](https://github.com/andrewheiss/SublimeStataEnhanced#os-x)

Once I get more time, it'd probably be useful to have an alternate build system for 13 that *does* use the Applescript command

**Comment by chrisbirdsall** [comment]
Ah... yes. That's what was preventing it from working (not setting .do files to open in Stata). My issue with that is I like to have do files set to open in sublime by default.
